name: ayrshare_flutter
description: Ayrshare Social Media Flutter Package
version: 0.1.0+1
homepage: https://github.com/akmadan/social_media_flutter

environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ">=0.13.0 <0.14.0"
  image_picker: ^0.8.6+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
