name: ayrshare_flutter
description: Add social media management to your app including posting, analytics, history, and much more.
version: 0.1.3+4
homepage: https://www.ayrshare.com
repository: https://github.com/ayrshare/ayrshare_flutter


environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ">=0.13.0 <0.14.0"
  image_picker: ^0.8.6+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
